// Package thesaurus answers "what else could I have said here" for a single
// word, from the condensed MyThes data generated by tools/mkthesaurus.
//
// Unlike the wordlist, this data is never handed to the app: at 3.5MB it is
// far too much to push across for a feature used a word at a time. The
// plugin keeps it and answers lookups instead, which is what the thesaurus
// capability is shaped for.
//
// It is also never fully parsed. The generated file is sorted, so Index
// records where each line starts and a lookup binary-searches those offsets
// and parses the one line it lands on. That keeps the resident cost to one
// offset per word -- a few hundred KB -- rather than the tens of megabytes a
// map of every entry would occupy inside the wasm instance.
package thesaurus

import (
	"sort"
	"strings"
)

// Sense is one meaning of a word, kept separate from the others because
// their synonyms are not interchangeable: the synonyms for "bank" as a place
// to keep money are wrong for its river sense.
type Sense struct {
	PartOfSpeech string   `json:"pos"`
	Synonyms     []string `json:"synonyms"`
	Antonyms     []string `json:"antonyms,omitempty"`
}

// Entry is everything known about one word. It mirrors the thesaurus
// capability's JSON schema exactly; this plugin is a separate Go module and
// deliberately takes no dependency on Bison Relay to get it.
type Entry struct {
	Word   string  `json:"word"`
	Senses []Sense `json:"senses"`
}

// Index is a searchable view over a generated thesaurus file.
type Index struct {
	data string
	// starts holds the byte offset of each entry line, in sorted-word order
	// (comment lines excluded), so a lookup is a binary search over them.
	starts []int
}

// NewIndex scans data once for line boundaries. It does not parse any entry.
func NewIndex(data string) *Index {
	idx := &Index{data: data}
	for offset := 0; offset < len(data); {
		end := strings.IndexByte(data[offset:], '\n')
		if end < 0 {
			end = len(data) - offset
		}
		if end > 0 && data[offset] != '#' {
			idx.starts = append(idx.starts, offset)
		}
		offset += end + 1
	}
	return idx
}

// Len reports how many words the index covers.
func (idx *Index) Len() int { return len(idx.starts) }

// headwordAt returns the word an entry line begins with, without parsing the
// rest of it.
func (idx *Index) headwordAt(i int) string {
	line := idx.data[idx.starts[i]:]
	if end := strings.IndexByte(line, '\n'); end >= 0 {
		line = line[:end]
	}
	if bar := strings.IndexByte(line, '|'); bar >= 0 {
		return line[:bar]
	}
	return line
}

// lineAt returns the whole entry line at i.
func (idx *Index) lineAt(i int) string {
	line := idx.data[idx.starts[i]:]
	if end := strings.IndexByte(line, '\n'); end >= 0 {
		line = line[:end]
	}
	return line
}

// Lookup returns the entry for word, or ok=false if the thesaurus has none.
func (idx *Index) Lookup(word string) (Entry, bool) {
	word = strings.ToLower(strings.TrimSpace(word))
	if word == "" {
		return Entry{}, false
	}

	i := sort.Search(len(idx.starts), func(i int) bool {
		return idx.headwordAt(i) >= word
	})
	if i >= len(idx.starts) || idx.headwordAt(i) != word {
		return Entry{}, false
	}
	return parseLine(idx.lineAt(i))
}

// parseLine reads one generated entry: word|pos:syn,syn|pos:syn!ant,ant
func parseLine(line string) (Entry, bool) {
	parts := strings.Split(line, "|")
	if len(parts) < 2 {
		return Entry{}, false
	}
	entry := Entry{Word: parts[0]}
	for _, raw := range parts[1:] {
		colon := strings.IndexByte(raw, ':')
		if colon < 0 {
			continue
		}
		sense := Sense{PartOfSpeech: raw[:colon]}
		body := raw[colon+1:]
		if bang := strings.IndexByte(body, '!'); bang >= 0 {
			sense.Antonyms = splitList(body[bang+1:])
			body = body[:bang]
		}
		sense.Synonyms = splitList(body)
		if len(sense.Synonyms) > 0 || len(sense.Antonyms) > 0 {
			entry.Senses = append(entry.Senses, sense)
		}
	}
	return entry, len(entry.Senses) > 0
}

func splitList(s string) []string {
	if s == "" {
		return nil
	}
	out := strings.Split(s, ",")
	kept := out[:0]
	for _, w := range out {
		if w = strings.TrimSpace(w); w != "" {
			kept = append(kept, w)
		}
	}
	if len(kept) == 0 {
		return nil
	}
	return kept
}
