package thesaurus

import "testing"

// sample mirrors the generated file's shape, comments and all, so the index
// is exercised against what it will really be handed.
const sample = `# Generated by tools/mkthesaurus -- do not edit.
# 4 entries.
apple|noun:orchard apple tree,Malus pumila
bank|noun:depository financial institution,banking concern|verb:trust,rely!mistrust
happy|adj:glad,cheerful,blissful!unhappy
zebra|noun:equid,equine
`

// defs mirrors the file tools/mkdefs generates. It deliberately does not
// cover the same words as sample: the two datasets are independent, and a
// word in one but not the other must still produce an answer.
const defs = `# Generated by tools/mkdefs -- do not edit.
# 3 words.
apple|noun:fruit with red or yellow or green skin
happy|adj:enjoying or showing or marked by joy|verb:not a real sense
otter|noun:freshwater carnivorous mammal
`

// exc mirrors the file tools/mkexceptions generates: the irregular forms no
// suffix rule reaches.
const exc = `# Generated by tools/mkexceptions -- do not edit.
# 2 irregular forms.
mice|mouse
zebras|zebra
`

func TestLookupFindsEntries(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")
	if idx.Len() != 4 {
		t.Fatalf("Len() = %d, want 4 (comment lines must not be indexed)", idx.Len())
	}

	got, ok := idx.Lookup("happy")
	if !ok {
		t.Fatal("Lookup(happy) found nothing")
	}
	if got.Word != "happy" {
		t.Errorf("Word = %q, want happy", got.Word)
	}
	if len(got.Senses) != 1 {
		t.Fatalf("Senses = %+v, want 1", got.Senses)
	}
	s := got.Senses[0]
	if s.PartOfSpeech != "adj" {
		t.Errorf("PartOfSpeech = %q, want adj", s.PartOfSpeech)
	}
	if len(s.Synonyms) != 3 || s.Synonyms[0] != "glad" {
		t.Errorf("Synonyms = %v", s.Synonyms)
	}
	if len(s.Antonyms) != 1 || s.Antonyms[0] != "unhappy" {
		t.Errorf("Antonyms = %v", s.Antonyms)
	}
}

// The first and last entries are where a binary search over line offsets
// goes wrong if the bounds are off by one.
func TestLookupFindsBoundaryEntries(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")
	for _, word := range []string{"apple", "zebra"} {
		if _, ok := idx.Lookup(word); !ok {
			t.Errorf("Lookup(%q) found nothing", word)
		}
	}
}

// Senses must stay apart: pooling "bank"'s money and river synonyms into one
// list is what makes a thesaurus give confidently wrong advice.
func TestLookupKeepsSensesSeparate(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")
	got, ok := idx.Lookup("bank")
	if !ok {
		t.Fatal("Lookup(bank) found nothing")
	}
	if len(got.Senses) != 2 {
		t.Fatalf("Senses = %+v, want 2", got.Senses)
	}
	if got.Senses[0].PartOfSpeech != "noun" || got.Senses[1].PartOfSpeech != "verb" {
		t.Errorf("parts of speech = %q, %q",
			got.Senses[0].PartOfSpeech, got.Senses[1].PartOfSpeech)
	}
	if len(got.Senses[0].Antonyms) != 0 {
		t.Errorf("the noun sense picked up the verb sense's antonyms: %v",
			got.Senses[0].Antonyms)
	}
}

func TestLookupMisses(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")
	// Words before, between and after the entries, plus the empty string:
	// each is a different way for a binary search to land wrongly. None
	// appears in either dataset.
	for _, word := range []string{"aardvark", "cat", "zzz", "", "   "} {
		if entry, ok := idx.Lookup(word); ok {
			t.Errorf("Lookup(%q) returned %+v, want no match", word, entry)
		}
	}
}

func TestLookupIsCaseAndSpaceInsensitive(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")
	for _, word := range []string{"Happy", "HAPPY", "  happy  "} {
		if _, ok := idx.Lookup(word); !ok {
			t.Errorf("Lookup(%q) found nothing", word)
		}
	}
}

func TestNewIndexHandlesNoTrailingNewline(t *testing.T) {
	idx := NewIndex("apple|noun:fruit", "", "", "")
	if idx.Len() != 1 {
		t.Fatalf("Len() = %d, want 1", idx.Len())
	}
	if _, ok := idx.Lookup("apple"); !ok {
		t.Error("Lookup(apple) found nothing")
	}
}

func TestLookupReturnsDefinitions(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")
	if idx.DefinitionsLen() != 3 {
		t.Fatalf("DefinitionsLen() = %d, want 3", idx.DefinitionsLen())
	}

	got, ok := idx.Lookup("happy")
	if !ok {
		t.Fatal("Lookup(happy) found nothing")
	}
	if len(got.Definitions) != 2 {
		t.Fatalf("Definitions = %+v, want 2", got.Definitions)
	}
	if got.Definitions[0].PartOfSpeech != "adj" {
		t.Errorf("PartOfSpeech = %q, want adj", got.Definitions[0].PartOfSpeech)
	}
	want := "enjoying or showing or marked by joy"
	if got.Definitions[0].Text != want {
		t.Errorf("Text = %q, want %q", got.Definitions[0].Text, want)
	}
	// The synonyms must still be there: one dataset answering must not
	// shadow the other.
	if len(got.Senses) != 1 {
		t.Errorf("Senses = %+v, want the synonyms as well", got.Senses)
	}
}

// A word in one dataset and not the other is the common case -- the two are
// built from different sources and cover different vocabularies -- so a
// half-answer has to be a real answer rather than a miss.
func TestLookupAnswersFromEitherDatasetAlone(t *testing.T) {
	idx := NewIndex(sample, defs, exc, "")

	got, ok := idx.Lookup("otter")
	if !ok {
		t.Fatal("Lookup(otter) found nothing, but it has a definition")
	}
	if len(got.Definitions) != 1 || len(got.Senses) != 0 {
		t.Errorf("otter = %+v, want a definition and no synonyms", got)
	}

	got, ok = idx.Lookup("zebra")
	if !ok {
		t.Fatal("Lookup(zebra) found nothing, but it has synonyms")
	}
	if len(got.Senses) != 1 || len(got.Definitions) != 0 {
		t.Errorf("zebra = %+v, want synonyms and no definition", got)
	}
}

// An index built without a definitions dataset is what an older generated
// build looks like, and must still answer from the synonyms.
func TestLookupWithoutDefinitions(t *testing.T) {
	idx := NewIndex(sample, "", "", "")
	got, ok := idx.Lookup("happy")
	if !ok {
		t.Fatal("Lookup(happy) found nothing")
	}
	if len(got.Definitions) != 0 {
		t.Errorf("Definitions = %+v, want none", got.Definitions)
	}
	if len(got.Senses) != 1 {
		t.Errorf("Senses = %+v, want 1", got.Senses)
	}
}
