// Package thesaurus answers "what else could I have said here" and "what
// does this mean" for a single word, from two condensed datasets: MyThes
// synonyms generated by tools/mkthesaurus, and WordNet definitions generated
// by tools/mkdefs.
//
// The two stay separate all the way through, including in the answer. They
// divide a word into different senses -- MyThes has its own grouping and
// WordNet has another -- so pairing a definition with a group of synonyms
// would mean guessing which meant which, and a wrong guess reads as
// confidently wrong rather than merely unhelpful.
//
// Both are keyed by base forms only -- "cat" and not "cats", "run" and not
// "running" -- which on its own leaves two thirds of the dictionary with
// nothing to look up. morphy.go reduces a word as typed to the forms they
// hold, and is why a lookup answers at all for most of what anyone selects.
//
// Unlike the wordlist, neither dataset is handed to the app: together they
// are 10MB, far too much to push across for a feature used a word at a time.
// The plugin keeps them and answers lookups instead, which is what the
// thesaurus capability is shaped for.
//
// Neither is fully parsed either. Both generated files are sorted, so the
// index records where each line starts and a lookup binary-searches those
// offsets and parses the one line it lands on. That keeps the resident cost
// to one offset per word -- a few hundred KB -- rather than the tens of
// megabytes a map of every entry would occupy inside the wasm instance.
package thesaurus

import (
	"sort"
	"strings"
)

// Sense is one meaning of a word, kept separate from the others because
// their synonyms are not interchangeable: the synonyms for "bank" as a place
// to keep money are wrong for its river sense.
type Sense struct {
	PartOfSpeech string   `json:"pos"`
	Synonyms     []string `json:"synonyms"`
	Antonyms     []string `json:"antonyms,omitempty"`
}

// Definition is one of a word's meanings.
type Definition struct {
	PartOfSpeech string `json:"pos"`
	Text         string `json:"text"`

	// Example is one sentence using the word in this sense, or empty when
	// the source had none. WordNet carries an example for 28% of its
	// synsets and they were being discarded; for a writing tool the example
	// is often the more useful half, since "marked by good fortune" settles
	// less than "a felicitous life" does.
	Example string `json:"example,omitempty"`
}

// Entry is everything known about one word. It mirrors the thesaurus
// capability's JSON schema exactly; this plugin is a separate Go module and
// deliberately takes no dependency on Bison Relay to get it.
type Entry struct {
	Word        string       `json:"word"`
	Senses      []Sense      `json:"senses"`
	Definitions []Definition `json:"definitions,omitempty"`

	// Inflections are the other forms the word takes: go/goes/went/gone,
	// child/children, happy/happier/happiest. Empty for a word that does not
	// inflect, and for a phrase.
	//
	// The same knowledge that reduces a word for lookup, pointed the other
	// way. It was held in one direction only, so the tool could find "child"
	// from "children" and could not say that "child" becomes "children".
	Inflections []string `json:"inflections,omitempty"`
}

// IsEmpty reports whether the entry says nothing, which is the ordinary
// outcome for a name, a typo, or a word neither dataset covers.
func (e Entry) IsEmpty() bool {
	// Inflections alone are not an answer: a list of forms with nothing
	// said about the word is a worse result than admitting there is none.
	return len(e.Senses) == 0 && len(e.Definitions) == 0
}

// lines is a sorted, pipe-delimited generated file viewed as searchable
// records, holding one offset per line rather than the parsed contents.
type lines struct {
	data string
	// starts holds the byte offset of each entry line, in sorted-word order
	// (comment lines excluded), so a lookup is a binary search over them.
	starts []int
}

// newLines scans data once for line boundaries. It parses nothing.
func newLines(data string) lines {
	var l lines
	l.data = data
	for offset := 0; offset < len(data); {
		end := strings.IndexByte(data[offset:], '\n')
		if end < 0 {
			end = len(data) - offset
		}
		if end > 0 && data[offset] != '#' {
			l.starts = append(l.starts, offset)
		}
		offset += end + 1
	}
	return l
}

// at returns the whole entry line at i.
func (l lines) at(i int) string {
	line := l.data[l.starts[i]:]
	if end := strings.IndexByte(line, '\n'); end >= 0 {
		line = line[:end]
	}
	return line
}

// headwordAt returns the word an entry line begins with, without parsing the
// rest of it.
func (l lines) headwordAt(i int) string {
	line := l.at(i)
	if bar := strings.IndexByte(line, '|'); bar >= 0 {
		return line[:bar]
	}
	return line
}

// find returns the line for word, or ok=false if there is none.
func (l lines) find(word string) (string, bool) {
	i := sort.Search(len(l.starts), func(i int) bool {
		return l.headwordAt(i) >= word
	})
	if i >= len(l.starts) || l.headwordAt(i) != word {
		return "", false
	}
	return l.at(i), true
}

// Index is a searchable view over the generated synonym and definition files,
// with the exception list that makes irregular words findable.
type Index struct {
	synonyms    lines
	definitions lines
	exceptions  lines
	inflections lines
}

// NewIndex scans the datasets once for line boundaries. Any of them may be
// empty, which yields an index that answers from whatever is left.
func NewIndex(synonymData, definitionData, exceptionData, inflectionData string) *Index {
	return &Index{
		synonyms:    newLines(synonymData),
		definitions: newLines(definitionData),
		inflections: newLines(inflectionData),
		exceptions:  newLines(exceptionData),
	}
}

// Len reports how many words have synonyms.
func (idx *Index) Len() int { return len(idx.synonyms.starts) }

// DefinitionsLen reports how many words have definitions.
func (idx *Index) DefinitionsLen() int { return len(idx.definitions.starts) }

// Lookup returns what is known about word, drawing on whichever datasets
// cover it. ok is false only when none of them do.
//
// The word is reduced to the forms the data is keyed by before each dataset
// is searched -- see morphy.go. The two datasets are reduced independently,
// because they were built from different sources and need not agree on which
// forms they hold: MyThes may have "running" where WordNet has only "run".
//
// Entry.Word reports the form actually answered for, which is not always the
// form asked about. Someone who selected "children" and is shown the entry
// for "child" should be told so rather than left to wonder whether the
// definition is really about the word they picked.
func (idx *Index) Lookup(word string) (Entry, bool) {
	// Collapsed as well as trimmed: a selection dragged across a line break
	// arrives with a newline in the middle of it, and the datasets are keyed
	// by single spaces.
	word = strings.ToLower(strings.Join(strings.Fields(word), " "))
	if word == "" {
		return Entry{}, false
	}

	forms := idx.candidates(word)
	entry := Entry{Word: word}

	for _, form := range forms {
		line, ok := idx.synonyms.find(form)
		if !ok {
			continue
		}
		if senses, ok := parseLine(line); ok {
			entry.Senses = senses.Senses
			entry.Word = form
			break
		}
	}
	for _, form := range forms {
		line, ok := idx.definitions.find(form)
		if !ok {
			continue
		}
		if defs := parseDefinitions(line); len(defs) > 0 {
			entry.Definitions = defs
			// The definition names the word more precisely than the synonyms
			// do, so it wins where the two reduced differently.
			entry.Word = form
			break
		}
	}
	// Inflections are looked up under whichever form actually answered, so
	// asking about "children" lists child/children rather than nothing.
	if line, ok := idx.inflections.find(entry.Word); ok {
		if _, forms, found := strings.Cut(line, "|"); found {
			entry.Inflections = splitList(forms)
		}
	}

	return entry, !entry.IsEmpty()
}

// parseDefinitions reads one generated line:
// word|pos:text~example|pos:text
//
// The example is optional and absent for most senses. A line written before
// examples existed has no tilde and parses to the same thing it always did.
func parseDefinitions(line string) []Definition {
	parts := strings.Split(line, "|")
	if len(parts) < 2 {
		return nil
	}
	var out []Definition
	for _, raw := range parts[1:] {
		pos, body, found := strings.Cut(raw, ":")
		if !found || strings.TrimSpace(body) == "" {
			continue
		}
		text, example, _ := strings.Cut(body, "~")
		if strings.TrimSpace(text) == "" {
			continue
		}
		out = append(out, Definition{
			PartOfSpeech: pos,
			Text:         strings.TrimSpace(text),
			Example:      strings.TrimSpace(example),
		})
	}
	return out
}

// parseLine reads one generated synonym entry:
// word|pos:syn,syn|pos:syn!ant,ant
func parseLine(line string) (Entry, bool) {
	parts := strings.Split(line, "|")
	if len(parts) < 2 {
		return Entry{}, false
	}
	entry := Entry{Word: parts[0]}
	for _, raw := range parts[1:] {
		colon := strings.IndexByte(raw, ':')
		if colon < 0 {
			continue
		}
		sense := Sense{PartOfSpeech: raw[:colon]}
		body := raw[colon+1:]
		if bang := strings.IndexByte(body, '!'); bang >= 0 {
			sense.Antonyms = splitList(body[bang+1:])
			body = body[:bang]
		}
		sense.Synonyms = splitList(body)
		if len(sense.Synonyms) > 0 || len(sense.Antonyms) > 0 {
			entry.Senses = append(entry.Senses, sense)
		}
	}
	return entry, len(entry.Senses) > 0
}

func splitList(s string) []string {
	if s == "" {
		return nil
	}
	out := strings.Split(s, ",")
	kept := out[:0]
	for _, w := range out {
		if w = strings.TrimSpace(w); w != "" {
			kept = append(kept, w)
		}
	}
	if len(kept) == 0 {
		return nil
	}
	return kept
}
