// Command mkdefs condenses WordNet's sense data into the definitions the
// plugin ships.
//
// WordNet stores a synset per line: an offset, some bookkeeping, the words
// that share the sense, the pointers to related senses, and finally, after a
// "|", the definition and some usage examples. Only the words and the
// definition are wanted here, so almost all of the 21MB is discarded.
//
// Definitions are kept separate from the synonyms in thesaurus.txt rather
// than merged into them, because the two sources do not divide a word into
// the same senses: MyThes has its own grouping, and lining WordNet's up with
// it would mean guessing which of its senses matched which of theirs. Listing
// them separately is honest about that.
//
// data/function-words.txt is merged in on top. WordNet holds only nouns,
// verbs, adjectives and adverbs, so it has nothing at all for "the", "of" or
// "although" -- and those are the words a reader is likeliest to select. See
// the note at the head of that file.
//
// Run from the repo root:
//
//	go run ./tools/mkdefs > definitions.txt
//
// Output is one line per word, sorted:
//
//	word|pos:definition|pos:definition
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	wordnetDir       = "data/wordnet"
	functionWordFile = "data/function-words.txt"
)

// maxDefinitions caps how many senses a word keeps. WordNet gives "run" over
// fifty; the first few carry the meanings anyone is looking up, and a menu
// showing them has to stay readable.
const maxDefinitions = 3

// files maps each data file to the part of speech it holds. WordNet's own
// codes are single letters; these are the labels shown to a reader.
var files = map[string]string{
	"data.noun": "noun",
	"data.verb": "verb",
	"data.adj":  "adj",
	"data.adv":  "adv",
}

type definition struct {
	pos  string
	text string
}

func main() {
	entries := map[string][]definition{}
	var synsets int

	for file, pos := range files {
		f, err := os.Open(filepath.Join(wordnetDir, file))
		if err != nil {
			fmt.Fprintln(os.Stderr, "mkdefs:", err)
			os.Exit(1)
		}
		sc := bufio.NewScanner(f)
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		for sc.Scan() {
			line := sc.Text()
			// The licence is printed at the top of every data file, indented
			// by two spaces; every real entry starts with its offset.
			if strings.HasPrefix(line, "  ") {
				continue
			}
			head, gloss, found := strings.Cut(line, "|")
			if !found {
				continue
			}
			// The gloss is the definition followed by quoted usage examples,
			// separated by semicolons. Only the definition is wanted.
			text := strings.TrimSpace(gloss)
			if i := strings.Index(text, ";"); i >= 0 {
				text = strings.TrimSpace(text[:i])
			}
			if text == "" {
				continue
			}
			synsets++

			// head is: offset lex_filenum ss_type w_cnt word lex_id [word
			// lex_id ...] p_cnt ... -- so the words start at field 4 and come
			// in pairs, and w_cnt is hexadecimal.
			fields := strings.Fields(head)
			if len(fields) < 5 {
				continue
			}
			count, err := strconv.ParseInt(fields[3], 16, 32)
			if err != nil {
				continue
			}
			for i := 0; i < int(count); i++ {
				at := 4 + i*2
				if at >= len(fields) {
					break
				}
				word := strings.ToLower(fields[at])
				if !usableHeadword(word) {
					continue
				}
				if len(entries[word]) >= maxDefinitions {
					continue
				}
				entries[word] = append(entries[word], definition{pos, text})
			}
		}
		f.Close()
		if err := sc.Err(); err != nil {
			fmt.Fprintln(os.Stderr, "mkdefs:", file+":", err)
			os.Exit(1)
		}
	}

	// Merged last and allowed to win: a hand-written gloss for "will" is
	// about the auxiliary, which is the sense anyone selecting it means,
	// where WordNet's entry is about willpower and a legal document.
	added := mergeFunctionWords(entries)

	words := make([]string, 0, len(entries))
	for w := range entries {
		words = append(words, w)
	}
	sort.Strings(words)

	out := bufio.NewWriter(os.Stdout)
	defer out.Flush()
	fmt.Fprintln(out, "# Generated by tools/mkdefs -- do not edit.")
	fmt.Fprintf(out, "# %d words condensed from %s.\n", len(words), wordnetDir)
	fmt.Fprintln(out, "# Licence and attribution: data/LICENSE-WORDNET31.")
	fmt.Fprintln(out, "# Format: word|pos:definition|pos:definition")
	var written int
	for _, w := range words {
		var b strings.Builder
		b.WriteString(w)
		for _, d := range entries[w] {
			b.WriteByte('|')
			b.WriteString(d.pos)
			b.WriteByte(':')
			// A definition cannot contain a pipe; WordNet uses it only as the
			// gloss separator. Newlines cannot occur at all.
			b.WriteString(strings.ReplaceAll(d.text, "|", "/"))
			written++
		}
		fmt.Fprintln(out, b.String())
	}
	fmt.Fprintf(os.Stderr,
		"mkdefs: %d words, %d definitions from %d synsets (+%d function words)\n",
		len(words), written, synsets, added)
}

// mergeFunctionWords reads the hand-written glosses and replaces whatever
// WordNet had for the same word.
//
// Replaces rather than appends. Several of these words do have a WordNet
// entry for an unrelated sense -- "will" as determination, "can" as a metal
// container, "may" as the month -- and listing those first under a word
// somebody selected for its grammatical use is worse than saying nothing.
func mergeFunctionWords(entries map[string][]definition) int {
	f, err := os.Open(functionWordFile)
	if err != nil {
		fmt.Fprintln(os.Stderr, "mkdefs:", err)
		os.Exit(1)
	}
	defer f.Close()

	var added int
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		word, body, found := strings.Cut(line, "|")
		if !found {
			continue
		}
		pos, text, found := strings.Cut(body, ":")
		if !found || strings.TrimSpace(text) == "" {
			continue
		}
		word = strings.ToLower(strings.TrimSpace(word))
		if _, seen := entries[word]; !seen {
			added++
		}
		entries[word] = []definition{{pos, strings.TrimSpace(text)}}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "mkdefs:", functionWordFile+":", err)
		os.Exit(1)
	}
	return added
}

// usableHeadword keeps only words a lookup could be triggered on: a single,
// purely alphabetic token. WordNet writes multi-word entries with
// underscores, which this rejects along with everything else.
func usableHeadword(w string) bool {
	if w == "" {
		return false
	}
	for _, r := range w {
		if r < 'a' || r > 'z' {
			return false
		}
	}
	return true
}
