// Command mkwords generates the plugin's wordlist for one language, from
// SCOWL's curated word lists in data/scowl, and merges data/extra-words.txt
// on top.
//
// SCOWL publishes plain lists of surface forms, split by how common each word
// is (the number on each filename: 10 is the commonest few thousand, 60 the
// tail of ordinary vocabulary) and by which English uses it. So a language is
// a choice of which files to read: everyone gets "english-", and then either
// "american-" or "british-".
//
// An earlier version expanded a hunspell dictionary instead -- roots plus
// affix flags, "abandon/LDGS" into the five words that spells. That worked
// for the American dictionary, whose affix file has 73 rules, and produced
// nonsense for the British one, whose 1,362 rules include productive
// derivational affixes that hunspell's own engine constrains in ways this
// tool did not: "underwearisable", "overnazismativeness",
// "miscorporativismativeness". Reimplementing hunspell correctly is a real
// project and not this one's, and SCOWL's lists need no engine at all --
// they are already the surface forms. The American list changed by 1% in the
// move, almost all of it obscure.
//
// Run from the repo root:
//
//	go run ./tools/mkwords -locale en-US > words-en-US.txt
//	go run ./tools/mkwords -locale en-GB > words-en-GB.txt
//
// The generated lists are committed, so building the plugin needs neither
// this tool nor data/scowl; both are kept so the lists are reproducible and
// auditable rather than opaque blobs.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	scowlDir  = "data/scowl"
	extraPath = "data/extra-words.txt"
)

// maxTier is how far down SCOWL's frequency ladder to read. 60 is the end of
// ordinary vocabulary; 70 and beyond is where the lists fill with technical
// and archaic words that nobody typing a chat message meant to write, so
// accepting them means real typos sail through unflagged.
const maxTier = 60

// minShortWordTier is how common a one- or two-letter entry must be to be
// kept. SCOWL carries hundreds of obscure two-letter abbreviations and
// symbols -- "th", "te", "aa", "bx" -- and accepting them means the most
// obvious typos in a chat sail through unflagged, with no correction offered
// because nothing was wrong. Below this tier they are dropped, so "th" is
// flagged and offered "the".
const minShortWordTier = 35

// commonTier is the ceiling for the ranked list the app uses to choose
// between equally-near corrections. Everything at 35 or below is a word
// people actually write.
const commonTier = 35

// locale is one language this plugin can check against: which of SCOWL's
// lists apply to it.
//
// "english-" is the shared core, and the variant prefix is what makes the
// two lists differ -- "colour" is in british-words and not in
// american-words, and "color" the other way round. The frequency ranking is
// split the same way, and has to be: a British checker ranking by American
// frequency would leave "colour" unranked, so a typo of it would be
// corrected to whatever else happened to be one edit away.
type locale struct {
	code     string
	name     string
	prefixes []string
}

// locales is the whole language list, and adding one is only data: SCOWL
// also publishes canadian- and australian- lists in the same shape.
var locales = []locale{
	{"en-US", "English (US)", []string{"english-", "american-"}},
	{"en-GB", "English (UK)", []string{"english-", "british-"}},
}

func find(code string) (locale, bool) {
	for _, l := range locales {
		if l.code == code {
			return l, true
		}
	}
	return locale{}, false
}

func main() {
	code := flag.String("locale", "en-US", "which language to build")
	flag.Parse()
	loc, ok := find(*code)
	if !ok {
		var codes []string
		for _, l := range locales {
			codes = append(codes, l.code)
		}
		fmt.Fprintf(os.Stderr, "mkwords: unknown locale %q; have %s\n",
			*code, strings.Join(codes, ", "))
		os.Exit(1)
	}

	tiers, err := readTiers(loc)
	if err != nil {
		fmt.Fprintln(os.Stderr, "mkwords:", scowlDir+":", err)
		os.Exit(1)
	}

	words := map[string]bool{}
	for w := range tiers {
		words[w] = true
	}
	fromScowl := len(words)

	if err := readExtra(extraPath, words); err != nil {
		fmt.Fprintln(os.Stderr, "mkwords:", extraPath+":", err)
		os.Exit(1)
	}

	// Drop the obscure very-short entries; see minShortWordTier.
	var droppedShort int
	for w := range words {
		if len(w) > 2 {
			continue
		}
		if tier, ok := tiers[w]; !ok || tier > minShortWordTier {
			delete(words, w)
			droppedShort++
		}
	}

	out := make([]string, 0, len(words))
	for w := range words {
		out = append(out, w)
	}
	sort.Strings(out)

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintln(w, "# Generated by tools/mkwords -- do not edit.")
	fmt.Fprintf(w, "# %s (%s): %d words, %d from %s and %d from %s.\n",
		loc.name, loc.code, len(out), fromScowl, scowlDir,
		len(words)-fromScowl, extraPath)
	fmt.Fprintln(w, "# Licence and attribution: data/LICENSE-SCOWL.")
	for _, word := range out {
		fmt.Fprintln(w, word)
	}

	common, err := writeCommon(loc, tiers, words)
	if err != nil {
		fmt.Fprintln(os.Stderr, "mkwords:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr,
		"mkwords: %s: %d words (%d obscure short entries dropped), %d ranked\n",
		loc.code, len(out), droppedShort, common)
}

// writeCommon writes the ranked subset the app uses to order corrections,
// commonest first.
func writeCommon(loc locale, tiers map[string]int, words map[string]bool) (int, error) {
	type ranked struct {
		word string
		tier int
	}
	var list []ranked
	for w, tier := range tiers {
		if tier <= commonTier && words[w] {
			list = append(list, ranked{w, tier})
		}
	}
	// By tier, then alphabetically, so the file is stable between runs --
	// map iteration order is not.
	sort.Slice(list, func(i, j int) bool {
		if list[i].tier != list[j].tier {
			return list[i].tier < list[j].tier
		}
		return list[i].word < list[j].word
	})

	f, err := os.Create("common-" + loc.code + ".txt")
	if err != nil {
		return 0, err
	}
	defer f.Close()
	out := bufio.NewWriter(f)
	defer out.Flush()
	fmt.Fprintln(out, "# Generated by tools/mkwords -- do not edit.")
	fmt.Fprintf(out, "# %s: %d words, most common first.\n", loc.code, len(list))
	for _, r := range list {
		fmt.Fprintln(out, r.word)
	}
	return len(list), nil
}

// readTiers loads every SCOWL list this locale uses, keyed by word, with the
// lowest tier each word appears at.
//
// The tier is what ranks corrections. Edit distance alone cannot: "teh" is
// one typo away from "the", "tech", "meh", "th" and "te" alike, and without
// knowing which of those people actually write, the intended word is as
// likely to be missing from the handful shown as not.
func readTiers(loc locale) (map[string]int, error) {
	entries, err := os.ReadDir(scowlDir)
	if err != nil {
		return nil, err
	}

	tiers := map[string]int{}
	for _, e := range entries {
		name := e.Name()

		var wanted bool
		for _, prefix := range loc.prefixes {
			if strings.HasPrefix(name, prefix) {
				wanted = true
				break
			}
		}
		if !wanted {
			continue
		}

		dot := strings.LastIndex(name, ".")
		if dot < 0 {
			continue
		}
		tier, err := strconv.Atoi(name[dot+1:])
		if err != nil || tier > maxTier {
			continue
		}

		f, err := os.Open(filepath.Join(scowlDir, name))
		if err != nil {
			return nil, err
		}
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			// The lists are ISO-8859-1, and accented words are folded rather
			// than dropped: "melee" and "emigre" are how people type mêlée
			// and émigré, and the checker's alphabet is ASCII.
			word := foldToASCII(sc.Text())
			if word == "" {
				continue
			}
			if prev, ok := tiers[word]; !ok || tier < prev {
				tiers[word] = tier
			}
		}
		f.Close()
		if err := sc.Err(); err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
	}
	return tiers, nil
}

// asciiFolds are the accented letters SCOWL's lists actually contain,
// decoded from ISO-8859-1 to the letter somebody would type instead.
var asciiFolds = map[rune]rune{
	'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a',
	'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e',
	'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i',
	'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o', 'ø': 'o',
	'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u',
	'ñ': 'n', 'ç': 'c', 'ý': 'y', 'ÿ': 'y',
}

// foldToASCII lowercases a SCOWL entry and reduces its accents, returning ""
// for anything that still is not a plain word.
func foldToASCII(line string) string {
	// The files are ISO-8859-1: each byte is one code point, which is what
	// ranging over the decoded string below assumes.
	var decoded []rune
	for _, b := range []byte(strings.TrimSpace(line)) {
		decoded = append(decoded, rune(b))
	}

	var b strings.Builder
	for _, r := range decoded {
		if fold, ok := asciiFolds[r]; ok {
			r = fold
		}
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + 32)
		case r >= 'a' && r <= 'z', r == '\'', r == '.', r == '-':
			b.WriteRune(r)
		default:
			// A word with anything else in it is not one this checker can
			// compare against.
			return ""
		}
	}
	return b.String()
}

// readExtra merges the supplemental vocabulary: words SCOWL does not carry
// but a Bison Relay user writes constantly.
func readExtra(path string, words map[string]bool) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.ToLower(strings.TrimSpace(sc.Text()))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		words[line] = true
	}
	return sc.Err()
}
