// Command mkexceptions condenses WordNet's irregular-inflection lists into
// the one file the plugin ships.
//
// WordNet's Morphy reduces a word to its base form with suffix rules, and
// keeps these lists for the words no rule reaches: went/go, children/child,
// better/good, mice/mouse. There are four, one per part of speech, and the
// plugin has no use for that division -- it wants to know what a word might
// be, not what part of speech it might be it as -- so they are merged.
//
// Run from the repo root:
//
//	go run ./tools/mkexceptions > exceptions.txt
//
// Output is one line per irregular form, sorted:
//
//	word|base,base
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const wordnetDir = "data/wordnet"

var files = []string{"noun.exc", "verb.exc", "adj.exc", "adv.exc"}

func main() {
	bases := map[string][]string{}
	seen := map[string]bool{}

	for _, name := range files {
		f, err := os.Open(filepath.Join(wordnetDir, name))
		if err != nil {
			fmt.Fprintln(os.Stderr, "mkexceptions:", err)
			os.Exit(1)
		}
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			// Each line is the inflected form followed by one or more base
			// forms, space separated.
			fields := strings.Fields(sc.Text())
			if len(fields) < 2 {
				continue
			}
			word := strings.ToLower(fields[0])
			// Multi-word entries are written with underscores and cannot be
			// reached by a single-word selection, which is all this is asked
			// about.
			if strings.ContainsAny(word, "_ ") {
				continue
			}
			for _, base := range fields[1:] {
				base = strings.ToLower(base)
				if strings.ContainsAny(base, "_ ") || base == word {
					continue
				}
				key := word + "\x00" + base
				if seen[key] {
					continue
				}
				seen[key] = true
				bases[word] = append(bases[word], base)
			}
		}
		f.Close()
		if err := sc.Err(); err != nil {
			fmt.Fprintln(os.Stderr, "mkexceptions:", name+":", err)
			os.Exit(1)
		}
	}

	words := make([]string, 0, len(bases))
	for w := range bases {
		words = append(words, w)
	}
	sort.Strings(words)

	out := bufio.NewWriter(os.Stdout)
	defer out.Flush()
	fmt.Fprintln(out, "# Generated by tools/mkexceptions -- do not edit.")
	fmt.Fprintf(out, "# %d irregular forms from %s.\n", len(words), wordnetDir)
	fmt.Fprintln(out, "# Licence and attribution: data/LICENSE-WORDNET31.")
	fmt.Fprintln(out, "# Format: word|base,base")
	for _, w := range words {
		fmt.Fprintf(out, "%s|%s\n", w, strings.Join(bases[w], ","))
	}
	fmt.Fprintf(os.Stderr, "mkexceptions: %d irregular forms\n", len(words))
}
